"""
GPT-Eval: GPT-4-as-judge evaluation framework for TinyStories.

Implements the novel evaluation paradigm from the paper where GPT-4 acts as
an automated teacher grading stories generated by smaller models. Each story
is scored on three dimensions (1-10 scale):

    1. Grammar    - Fluency, correctness, and syntactic structure
    2. Creativity - Originality, diversity, and engagement
    3. Consistency - Narrative coherence, character identity, and logical flow

The paper argues this multi-dimensional evaluation provides richer insight
than standard benchmarks (e.g., perplexity) which only capture a single
aggregate metric and often require structured outputs.

Usage:
    python -m tinystories.evaluate \
        --checkpoint checkpoints/tiny-3M/best.pt \
        --num_prompts 50 \
        --output_file results/eval_tiny3M.json

Reference: Section 5 of Eldan & Li (2023), arXiv:2305.07759
"""

import argparse
import json
import logging
import os
import time
from pathlib import Path
from typing import Dict, List, Optional

import torch

from tinystories.generate import (
    DEFAULT_PROMPTS,
    generate_story,
    load_model_from_checkpoint,
)

logger = logging.getLogger(__name__)

# ============================================================================
# GPT-4 Evaluation Prompt (following the paper's grading rubric)
# ============================================================================

EVAL_SYSTEM_PROMPT = """You are an expert evaluator of children's stories. You will be given a story \
written by a language model and must grade it on three dimensions. Be fair but rigorous.

For each dimension, provide a score from 1 to 10:

1. **Grammar** (1-10): How fluent and grammatically correct is the story? \
Does it use proper sentence structure, punctuation, and word usage? \
A score of 10 means perfect grammar throughout. A score of 1 means the text \
is largely incomprehensible or contains severe grammatical errors in nearly every sentence.

2. **Creativity** (1-10): How original, engaging, and imaginative is the story? \
Does it go beyond simple, repetitive patterns? Does it introduce interesting \
characters, events, or ideas? A score of 10 means highly creative and engaging. \
A score of 1 means extremely repetitive or formulaic with no interesting elements.

3. **Consistency** (1-10): How well does the story maintain narrative coherence? \
Do characters remain consistent? Does the plot follow a logical sequence? \
Is the story self-consistent without contradictions? A score of 10 means \
perfectly coherent throughout. A score of 1 means the text contradicts itself \
or has no logical flow."""

EVAL_USER_TEMPLATE = """Please evaluate the following story that was generated by a language model \
given the prompt: "{prompt}"

--- BEGIN STORY ---
{story}
--- END STORY ---

Respond with ONLY a JSON object in the following format (no other text):
{{
    "grammar": <score 1-10>,
    "creativity": <score 1-10>,
    "consistency": <score 1-10>,
    "explanation": "<brief explanation of your scores>"
}}"""


def evaluate_single_story(
    client,
    story: str,
    prompt: str,
    eval_model: str = "gpt-4",
    max_retries: int = 3,
) -> Optional[Dict]:
    """Evaluate a single story using GPT-4.

    Args:
        client: OpenAI client instance.
        story: The generated story text to evaluate.
        prompt: The original prompt used to generate the story.
        eval_model: OpenAI model to use as evaluator.
        max_retries: Maximum API retry attempts.

    Returns:
        Dictionary with scores {grammar, creativity, consistency, explanation}
        or None on failure.
    """
    eval_prompt = EVAL_USER_TEMPLATE.format(prompt=prompt, story=story)

    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=eval_model,
                messages=[
                    {"role": "system", "content": EVAL_SYSTEM_PROMPT},
                    {"role": "user", "content": eval_prompt},
                ],
                temperature=0.0,  # Deterministic evaluation
                max_tokens=300,
            )

            result_text = response.choices[0].message.content.strip()

            # Parse JSON response
            # Handle potential markdown code blocks
            if result_text.startswith("```"):
                result_text = result_text.split("```")[1]
                if result_text.startswith("json"):
                    result_text = result_text[4:]
                result_text = result_text.strip()

            scores = json.loads(result_text)

            # Validate scores
            for key in ["grammar", "creativity", "consistency"]:
                if key not in scores:
                    raise ValueError(f"Missing key: {key}")
                score = scores[key]
                if not isinstance(score, (int, float)) or score < 1 or score > 10:
                    raise ValueError(f"Invalid score for {key}: {score}")

            return scores

        except json.JSONDecodeError as e:
            logger.warning(
                f"JSON parse error (attempt {attempt + 1}/{max_retries}): {e}"
            )
            time.sleep(1)
        except Exception as e:
            wait_time = 2 ** attempt
            logger.warning(
                f"Evaluation error (attempt {attempt + 1}/{max_retries}): {e}. "
                f"Retrying in {wait_time}s..."
            )
            time.sleep(wait_time)

    logger.error("Failed to evaluate story after all retries.")
    return None


def evaluate_model(
    checkpoint_path: str,
    prompts: List[str] = None,
    num_completions: int = 10,
    max_new_tokens: int = 200,
    temperature: float = 1.0,
    eval_model: str = "gpt-4",
    output_file: str = None,
    device_str: str = "auto",
) -> Dict:
    """Full evaluation pipeline: generate stories and grade them with GPT-4.

    Following the paper's methodology:
    1. For each prompt, generate `num_completions` stories at temperature=1.0
    2. Send each story to GPT-4 for grading on grammar, creativity, consistency
    3. Average scores across all completions and prompts
    4. Report per-prompt and aggregate scores

    Args:
        checkpoint_path: Path to the trained model checkpoint.
        prompts: List of prompts (defaults to paper's evaluation set).
        num_completions: Number of completions per prompt (paper uses 10).
        max_new_tokens: Maximum tokens per generated story.
        temperature: Generation temperature (paper uses 1.0 for eval).
        eval_model: OpenAI model for evaluation.
        output_file: Path to save evaluation results.
        device_str: Device for the generator model.

    Returns:
        Dictionary with per-prompt scores and aggregate statistics.
    """
    try:
        from openai import OpenAI
    except ImportError:
        raise ImportError(
            "openai package is required for evaluation. "
            "Install it with: pip install 'tinystories[eval]'"
        )

    client = OpenAI()

    if prompts is None:
        prompts = DEFAULT_PROMPTS

    # Determine device
    if device_str == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(device_str)

    # Load the model
    model, tokenizer, config = load_model_from_checkpoint(checkpoint_path, device)

    results = {
        "checkpoint": checkpoint_path,
        "eval_model": eval_model,
        "num_completions": num_completions,
        "temperature": temperature,
        "per_prompt": [],
        "aggregate": {},
    }

    all_grammar = []
    all_creativity = []
    all_consistency = []

    for i, prompt in enumerate(prompts):
        logger.info(f"Evaluating prompt {i+1}/{len(prompts)}: '{prompt[:50]}...'")

        prompt_scores = {
            "prompt": prompt,
            "completions": [],
            "avg_grammar": 0.0,
            "avg_creativity": 0.0,
            "avg_consistency": 0.0,
        }

        prompt_grammar = []
        prompt_creativity = []
        prompt_consistency = []

        for j in range(num_completions):
            # Generate story
            story = generate_story(
                model, tokenizer, prompt,
                max_new_tokens=max_new_tokens,
                temperature=temperature,
                top_k=50,
                top_p=0.9,
                device=device,
            )

            # Evaluate with GPT-4
            scores = evaluate_single_story(client, story, prompt, eval_model)

            if scores:
                completion_result = {
                    "story": story,
                    "scores": scores,
                }
                prompt_scores["completions"].append(completion_result)
                prompt_grammar.append(scores["grammar"])
                prompt_creativity.append(scores["creativity"])
                prompt_consistency.append(scores["consistency"])

                logger.info(
                    f"  Completion {j+1}/{num_completions}: "
                    f"G={scores['grammar']}, "
                    f"C={scores['creativity']}, "
                    f"Co={scores['consistency']}"
                )
            else:
                logger.warning(f"  Completion {j+1}/{num_completions}: evaluation failed")

            # Rate limiting
            time.sleep(1.0)

        # Per-prompt averages
        if prompt_grammar:
            prompt_scores["avg_grammar"] = sum(prompt_grammar) / len(prompt_grammar)
            prompt_scores["avg_creativity"] = sum(prompt_creativity) / len(prompt_creativity)
            prompt_scores["avg_consistency"] = sum(prompt_consistency) / len(prompt_consistency)

            all_grammar.extend(prompt_grammar)
            all_creativity.extend(prompt_creativity)
            all_consistency.extend(prompt_consistency)

        results["per_prompt"].append(prompt_scores)

        logger.info(
            f"  Prompt avg: Grammar={prompt_scores['avg_grammar']:.1f}, "
            f"Creativity={prompt_scores['avg_creativity']:.1f}, "
            f"Consistency={prompt_scores['avg_consistency']:.1f}"
        )

    # Aggregate scores
    if all_grammar:
        results["aggregate"] = {
            "grammar": {
                "mean": sum(all_grammar) / len(all_grammar),
                "min": min(all_grammar),
                "max": max(all_grammar),
            },
            "creativity": {
                "mean": sum(all_creativity) / len(all_creativity),
                "min": min(all_creativity),
                "max": max(all_creativity),
            },
            "consistency": {
                "mean": sum(all_consistency) / len(all_consistency),
                "min": min(all_consistency),
                "max": max(all_consistency),
            },
            "n_evaluated": len(all_grammar),
            "n_prompts": len(prompts),
        }

    # Print summary
    print("\n" + "=" * 60)
    print("GPT-Eval Results Summary")
    print("=" * 60)
    if results["aggregate"]:
        agg = results["aggregate"]
        print(f"  Stories evaluated: {agg['n_evaluated']}")
        print(f"  Grammar:     {agg['grammar']['mean']:.2f} "
              f"(min={agg['grammar']['min']}, max={agg['grammar']['max']})")
        print(f"  Creativity:  {agg['creativity']['mean']:.2f} "
              f"(min={agg['creativity']['min']}, max={agg['creativity']['max']})")
        print(f"  Consistency: {agg['consistency']['mean']:.2f} "
              f"(min={agg['consistency']['min']}, max={agg['consistency']['max']})")
    print("=" * 60 + "\n")

    # Save results
    if output_file:
        out_path = Path(output_file)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w") as f:
            json.dump(results, f, indent=2)
        logger.info(f"Results saved to {output_file}")

    return results


def main():
    parser = argparse.ArgumentParser(
        description="Evaluate a TinyStories model using GPT-4 (GPT-Eval)"
    )
    parser.add_argument(
        "--checkpoint", type=str, required=True,
        help="Path to model checkpoint (.pt file)",
    )
    parser.add_argument(
        "--eval_model", type=str, default="gpt-4",
        help="OpenAI model for evaluation (default: gpt-4)",
    )
    parser.add_argument(
        "--num_prompts", type=int, default=None,
        help="Number of prompts to evaluate (default: all 10)",
    )
    parser.add_argument(
        "--num_completions", type=int, default=10,
        help="Completions per prompt (default: 10, matching the paper)",
    )
    parser.add_argument(
        "--max_tokens", type=int, default=200,
        help="Max tokens per generated story",
    )
    parser.add_argument(
        "--temperature", type=float, default=1.0,
        help="Generation temperature (default: 1.0, matching the paper)",
    )
    parser.add_argument(
        "--output_file", type=str, default="results/evaluation.json",
        help="Output JSON file for results",
    )
    parser.add_argument(
        "--prompt_file", type=str, default=None,
        help="Custom prompts file (one per line)",
    )
    parser.add_argument(
        "--device", type=str, default="auto",
        help="Device: auto/cuda/cpu/mps",
    )

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    if not os.environ.get("OPENAI_API_KEY"):
        print("Error: OPENAI_API_KEY environment variable not set.")
        print("Export your key: export OPENAI_API_KEY='your-key-here'")
        return

    # Load prompts
    prompts = DEFAULT_PROMPTS
    if args.prompt_file:
        with open(args.prompt_file, "r") as f:
            prompts = [line.strip() for line in f if line.strip()]
    if args.num_prompts:
        prompts = prompts[:args.num_prompts]

    evaluate_model(
        checkpoint_path=args.checkpoint,
        prompts=prompts,
        num_completions=args.num_completions,
        max_new_tokens=args.max_tokens,
        temperature=args.temperature,
        eval_model=args.eval_model,
        output_file=args.output_file,
        device_str=args.device,
    )


if __name__ == "__main__":
    main()
