"""
Synthetic story generation using the OpenAI API.

Implements the dataset creation pipeline from Section 2 of the TinyStories paper.
Stories are generated by prompting GPT-3.5/GPT-4 with randomly sampled vocabulary
constraints and narrative features to produce a diverse corpus of simple children's
stories suitable for training small language models.

Usage:
    python -m tinystories.data.generate_stories \
        --model gpt-4 \
        --num_stories 1000 \
        --output_file data/custom_stories.json
"""

import argparse
import json
import logging
import os
import random
import time
from pathlib import Path
from typing import Dict, List, Optional

from tinystories.data.vocabulary import (
    build_generation_prompt,
    build_instruct_prompt,
    sample_story_seed,
)

logger = logging.getLogger(__name__)


def generate_single_story(
    client,
    model: str,
    noun: str,
    verb: str,
    adjective: str,
    features: List[str],
    instruct: bool = False,
    temperature: float = 1.0,
    max_retries: int = 3,
) -> Optional[Dict]:
    """Generate a single story via the OpenAI API.

    Args:
        client: OpenAI client instance.
        model: Model name (e.g., 'gpt-4', 'gpt-3.5-turbo').
        noun: Required noun for the story.
        verb: Required verb for the story.
        adjective: Required adjective for the story.
        features: Narrative features to include.
        instruct: If True, use the instruct variant with additional constraints.
        temperature: Sampling temperature.
        max_retries: Maximum API retry attempts.

    Returns:
        Dictionary with story text and metadata, or None on failure.
    """
    if instruct:
        prompt = build_instruct_prompt(noun, verb, adjective, features)
    else:
        prompt = build_generation_prompt(noun, verb, adjective, features)

    system_msg = (
        "You are a helpful assistant that writes short, simple stories for young "
        "children. Use only words that a 3-4 year old would understand. Keep the "
        "stories between 3-5 short paragraphs."
    )

    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_msg},
                    {"role": "user", "content": prompt},
                ],
                temperature=temperature,
                max_tokens=500,
            )
            story_text = response.choices[0].message.content.strip()

            return {
                "story": story_text,
                "noun": noun,
                "verb": verb,
                "adjective": adjective,
                "features": features,
                "model": model,
                "prompt": prompt,
            }

        except Exception as e:
            wait_time = 2 ** attempt
            logger.warning(
                f"API error (attempt {attempt + 1}/{max_retries}): {e}. "
                f"Retrying in {wait_time}s..."
            )
            time.sleep(wait_time)

    logger.error(f"Failed to generate story after {max_retries} attempts.")
    return None


def generate_dataset(
    model: str = "gpt-3.5-turbo",
    num_stories: int = 1000,
    output_file: str = "data/custom_stories.json",
    instruct: bool = False,
    seed: int = 42,
    temperature: float = 1.0,
    batch_save_every: int = 100,
) -> List[Dict]:
    """Generate a full dataset of stories.

    Implements the systematic prompt-engineering strategy from the paper:
    for each story, randomly sample one verb, one noun, one adjective, and
    0-3 narrative features, then prompt a large LM to generate the story.

    Args:
        model: OpenAI model to use for generation.
        num_stories: Total number of stories to generate.
        output_file: Path to save the generated dataset (JSON).
        instruct: Whether to use the instruct variant.
        seed: Random seed for reproducibility.
        temperature: Sampling temperature for generation.
        batch_save_every: Save intermediate results every N stories.

    Returns:
        List of generated story dictionaries.
    """
    try:
        from openai import OpenAI
    except ImportError:
        raise ImportError(
            "openai package is required for story generation. "
            "Install it with: pip install openai"
        )

    client = OpenAI()  # Uses OPENAI_API_KEY from environment
    rng = random.Random(seed)
    stories = []

    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Resume from existing file if it exists
    if output_path.exists():
        with open(output_path, "r") as f:
            stories = json.load(f)
        logger.info(f"Resuming from {len(stories)} existing stories.")

    start_idx = len(stories)

    for i in range(start_idx, num_stories):
        noun, verb, adjective, features = sample_story_seed(rng)

        story = generate_single_story(
            client=client,
            model=model,
            noun=noun,
            verb=verb,
            adjective=adjective,
            features=features,
            instruct=instruct,
            temperature=temperature,
        )

        if story:
            story["index"] = i
            stories.append(story)
            logger.info(
                f"[{i + 1}/{num_stories}] Generated story with "
                f"noun='{noun}', verb='{verb}', adj='{adjective}'"
            )
        else:
            logger.warning(f"[{i + 1}/{num_stories}] Skipped (generation failed)")

        # Periodic save
        if (i + 1) % batch_save_every == 0:
            with open(output_path, "w") as f:
                json.dump(stories, f, indent=2)
            logger.info(f"Saved {len(stories)} stories to {output_path}")

        # Rate limiting: small delay between requests
        time.sleep(0.5)

    # Final save
    with open(output_path, "w") as f:
        json.dump(stories, f, indent=2)
    logger.info(f"Dataset generation complete. {len(stories)} stories saved to {output_path}")

    return stories


def main():
    parser = argparse.ArgumentParser(
        description="Generate TinyStories dataset using OpenAI API"
    )
    parser.add_argument(
        "--model", type=str, default="gpt-3.5-turbo",
        help="OpenAI model to use (default: gpt-3.5-turbo)",
    )
    parser.add_argument(
        "--num_stories", type=int, default=1000,
        help="Number of stories to generate (default: 1000)",
    )
    parser.add_argument(
        "--output_file", type=str, default="data/custom_stories.json",
        help="Output JSON file path (default: data/custom_stories.json)",
    )
    parser.add_argument(
        "--instruct", action="store_true",
        help="Generate TinyStories-Instruct variant with additional constraints",
    )
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument(
        "--temperature", type=float, default=1.0, help="Sampling temperature"
    )

    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    if not os.environ.get("OPENAI_API_KEY"):
        print("Error: OPENAI_API_KEY environment variable not set.")
        print("Export your key: export OPENAI_API_KEY='your-key-here'")
        return

    generate_dataset(
        model=args.model,
        num_stories=args.num_stories,
        output_file=args.output_file,
        instruct=args.instruct,
        seed=args.seed,
        temperature=args.temperature,
    )


if __name__ == "__main__":
    main()
